# **AI ML Symposium 2019**

# **Introduction to Python for Data Analysis**

## *Topics*

1. Varibales
2. Commenting
3. Conditionals
4. List, Tuples and Dictionary
5. Loops
6. List Comprehension
7. Zip and Enumerate
8. Functions

#### Authors: Sudhindra Gopal Krishna and Aditya Narasimhan

### Variables and Commenting

In [4]:
# types of variables
number = 5
name = "AI ML Symposium"
place = 'The University of Oklahoma'

In [5]:
# display what variables hold
print(number)
print(name)
print(place)

5
AI ML Symposium
The University of Oklahoma


In [6]:
# display everything together
print("Display everything at once")
print(name + " at " + place)

Display everything at once
AI ML Symposium at The University of Oklahoma


In [7]:
# variable names are case sensitive
number = 10
Number = 11

print("The 'number' is ", number)
print("The 'Number' is ", Number)

The 'number' is  10
The 'Number' is  11


### *Conditional Statements*

Logical operators used in conditional statements

1. **Equals** : To check if two members are equal, **operator: ==**
2. **Not Equals** : To check if two members are not equal, **operator: !=**
3. **Less than** : To check if one member is less than the other, **operator: <**
4. **Less than or equal to** : To check if one member is less than or equal to the other, **operator: <=**
5. **Greater than** : To check if one member is greater than the other, **operator: >**
6. **Greater than or equal to** : To check if one member is greater than or equal to the other, **operator: >=**
7. **and operator** : Returns true if both the statements are true, **operator: and**
8. **or operator** : Returns true if either of the statements is true, **operator: or**

#### if, if-else, if-elif statements

In [8]:
number = 1000
max_number = 120

# want to check if the number is greater than maximum number
if number > max_number:
    print("The maximum number is ", number)
    

The maximum number is  1000


In [9]:
# want to check if the number is less than maximum number
# else we will say no it is not less than the maximum

if number < max_number:
    print("The number is less than the maximum number")
else:
    print("The number is not the maximum number")
    

The number is not the maximum number


In [10]:
# now what if we want to check if two numbers are equal
# if not we want to check if one number is greater than other
# if not we can confirm that the number is less than the other

if number == max_number:
    print("The number is equal to the maximum number")
elif number > max_number:
    print("The number is greater than the maximum number")
else:
    print("The number is lesser than the maximum number")
    

The number is greater than the maximum number


### List, Tuples, and Dictinoaries

In [11]:
numberList = [1, 2, 3, 4]
nameList = ["John", "Kane", "Ben", "Smith"]
combinedList = ["A", 56, 'C', 90 ]

#using list function
listFunction = list(range(0,9,2))

In [12]:
print(numberList)

[1, 2, 3, 4]


In [13]:
print(nameList)

['John', 'Kane', 'Ben', 'Smith']


In [14]:
print(combinedList)

['A', 56, 'C', 90]


In [15]:
print(listFunction)

[0, 2, 4, 6, 8]


In [17]:
print(listFunction[::-1]) # reverse the list

[8, 6, 4, 2, 0]


In [19]:
listFunction[1] = 10 # updating specific list value
print(listFunction)

[0, 10, 4, 6, 8]


In [22]:
if 11 in listFunction:
    print(True)
else:
    print(False)

False


### Numpy examples

In [39]:
# Numpy package import
import numpy as np

In [28]:
np.sort(nameList) # converted to a numpy array and then sorted

array(['Ben', 'John', 'Kane', 'Smith'], dtype='<U5')

In [30]:
# Use of tuples
tuples = ("John", "Kane", "Ben", "Smith")

In [31]:
np.sort(tuples)

array(['Ben', 'John', 'Kane', 'Smith'], dtype='<U5')

In [32]:
# Use of sets
sets = {"John", "Kane", "Ben", "Smith", "Kane"}

In [33]:
print(sets)

{'John', 'Smith', 'Kane', 'Ben'}


In [34]:
# Use of Dictinoray
# dictionary structure is key value pair

carDict = {"model" : ["Toyota", "Honda"],
           "make" : ["Supra", "S2000"],
          "engine" : ["2JZ", "F20C"],
          "year" : [1998, 2000]}

In [36]:
carDict['model'] # access values using key

['Toyota', 'Honda']

In [45]:
# import various datasets from the sklearn package
from sklearn import datasets
dataset = datasets.load_iris()

In [74]:
dataset.data

In [62]:
dataset.data[0] # access the first row of the dataset

array([5.1, 3.5, 1.4, 0.2])

In [86]:
dataset.data[:5] # access the first 5 rows of the dataset

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [110]:
np.sum(dataset.data[:5,:2], axis=1) # add the first 2 columns in numpy array

array([8.6, 7.9, 7.9, 7.7, 8.6])

In [113]:
np.add(dataset.data[0], dataset.data[1]) # add 2 rows in a numpy array

array([10. ,  6.5,  2.8,  0.4])

### Pandas examples

In [114]:
# Pandas package import
import pandas as pd

In [115]:
dataframe = pd.DataFrame(carDict) # create a dataframe 

In [116]:
dataframe #display a dataframe

model   make engine  year
0  Toyota  Supra    2JZ  1998
1   Honda  S2000   F20C  2000

In [144]:
dataframe["make"] # access a column in a dataframe

0    Supra
1    S2000
Name: make, dtype: object

In [136]:
dataframe.iloc[0] # access a row in a dataframe

model     Toyota
make       Supra
engine       2JZ
year        1998
Name: 0, dtype: object

In [137]:
irisSubset = dataset.data[0:100,0:3] # creating a subset of iris numpy dataset

In [141]:
newDF = pd.DataFrame(irisSubset) # create a dataframe from that subset

In [149]:
newDF.head() # display the first 5 rows

0    1    2
0  5.1  3.5  1.4
1  4.9  3.0  1.4
2  4.7  3.2  1.3
3  4.6  3.1  1.5
4  5.0  3.6  1.4

In [170]:
trainData = newDF[0] # store a column for later use

In [147]:
testData = newDF[1]

In [127]:
print(testData)

In [164]:
newDF.to_csv("test.csv") # save the dataframe as a csv file

In [165]:
newDF2 = pd.DataFrame() # declare new pandas dataframe object

In [166]:
newDF2 = pd.read_csv("test.csv") # read from a csv file

In [167]:
newDF2.head() # has the index from previous as the first column

Unnamed: 0    0    1    2
0           0  5.1  3.5  1.4
1           1  4.9  3.0  1.4
2           2  4.7  3.2  1.3
3           3  4.6  3.1  1.5
4           4  5.0  3.6  1.4

In [169]:
newDF2.drop(columns = ["Unnamed: 0"]) # delete the entire first column

newDF2 = pd.read_csv("test.csv")

### Loops

In [171]:
# While loop
i = 0 # index to keep track of the count

while(i<5):
    print(i)
    i+=1

0
1
2
3
4


In [172]:
# for loop
for i in range(0,5):
    print(i)

0
1
2
3
4


In [177]:
# print the items in a list
for items in nameList:
    print(items)

John
Kane
Ben
Smith


In [176]:
# find the cummulative sum of a list
print(listFunction)
sum = 0
for numbers in listFunction:
    sum += numbers

print(sum)

[0, 10, 4, 6, 8]
28


In [175]:
# loop through the elements of a dictionary with key and value
for key, value in carDict.items():
    
    print(key, " : ", value)

model  :  ['Toyota', 'Honda']
make  :  ['Supra', 'S2000']
engine  :  ['2JZ', 'F20C']
year  :  [1998, 2000]


## List Comprehension

In [178]:
# get even numbers from 0 to 21
evens = [] # delare an empty list

for i in range(0,21):
    if i%2 == 0:
        evens.append(i)

print(evens)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20]


In [179]:
# want to create a list of even numbers ranging from 0 to 20

evenNumbers = [x for x in range(0,21) if x%2 == 0]

In [180]:
print(evenNumbers)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20]


## Zip and Enumerate

In [181]:
# Enumurate: combine the index and the corresponding value of a list
for i in enumerate(evenNumbers):
    print(i)

(0, 0)
(1, 2)
(2, 4)
(3, 6)
(4, 8)
(5, 10)
(6, 12)
(7, 14)
(8, 16)
(9, 18)
(10, 20)


In [184]:
oddNumbers = [x for x in range(0,22) if x%2!=0] # create odd number of same length

In [185]:
# combine two lists of same length
for i in zip(evenNumbers, oddNumbers):
    print(i)

(0, 1)
(2, 3)
(4, 5)
(6, 7)
(8, 9)
(10, 11)
(12, 13)
(14, 15)
(16, 17)
(18, 19)
(20, 21)


In [190]:
iris[:5, :] # revisiting iris numpy array

array([[5.1, 3.5, 1.4],
       [4.9, 3. , 1.4],
       [4.7, 3.2, 1.3],
       [4.6, 3.1, 1.5],
       [5. , 3.6, 1.4]])

In [191]:
# use enumurate and zip together
for i in enumerate(zip(iris[:,0], iris[:,1])):
    print(i)

(0, (5.1, 3.5))
(1, (4.9, 3.0))
(2, (4.7, 3.2))
(3, (4.6, 3.1))
(4, (5.0, 3.6))
(5, (5.4, 3.9))
(6, (4.6, 3.4))
(7, (5.0, 3.4))
(8, (4.4, 2.9))
(9, (4.9, 3.1))
(10, (5.4, 3.7))
(11, (4.8, 3.4))
(12, (4.8, 3.0))
(13, (4.3, 3.0))
(14, (5.8, 4.0))
(15, (5.7, 4.4))
(16, (5.4, 3.9))
(17, (5.1, 3.5))
(18, (5.7, 3.8))
(19, (5.1, 3.8))
(20, (5.4, 3.4))
(21, (5.1, 3.7))
(22, (4.6, 3.6))
(23, (5.1, 3.3))
(24, (4.8, 3.4))
(25, (5.0, 3.0))
(26, (5.0, 3.4))
(27, (5.2, 3.5))
(28, (5.2, 3.4))
(29, (4.7, 3.2))
(30, (4.8, 3.1))
(31, (5.4, 3.4))
(32, (5.2, 4.1))
(33, (5.5, 4.2))
(34, (4.9, 3.1))
(35, (5.0, 3.2))
(36, (5.5, 3.5))
(37, (4.9, 3.6))
(38, (4.4, 3.0))
(39, (5.1, 3.4))
(40, (5.0, 3.5))
(41, (4.5, 2.3))
(42, (4.4, 3.2))
(43, (5.0, 3.5))
(44, (5.1, 3.8))
(45, (4.8, 3.0))
(46, (5.1, 3.8))
(47, (4.6, 3.2))
(48, (5.3, 3.7))
(49, (5.0, 3.3))
(50, (7.0, 3.2))
(51, (6.4, 3.2))
(52, (6.9, 3.1))
(53, (5.5, 2.3))
(54, (6.5, 2.8))
(55, (5.7, 2.8))
(56, (6.3, 3.3))
(57, (4.9, 2.4))
(58, (6.6, 2.9))
(59, (5

## Functions

In [193]:
import random # importing the random package

# function definition
def generateRandomNumbers(range1, range2, numElements): # attributes here are range1, range 2 and numElements
    
    randomNumbers = []
    
    for i in range(0, numElements+1):
        randomNumbers.append(random.randrange(range1, range2, 1))
        
    return randomNumbers

In [194]:
# function call
randNumbers = generateRandomNumbers(0, 20, 5)

In [195]:
randNumbers

[5, 16, 2, 5, 11, 19]

In [196]:
randNumbers2 = generateRandomNumbers(100, 300, 10)

In [197]:
randNumbers2

[241, 165, 207, 154, 294, 226, 182, 269, 183, 161, 257]